version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: pip install
          command: pip install .[dev]
      - run:
          name: Run tests
          command: python -m pytest
      - run:
          name: Run linter
          command: python -m pylint web tests

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test
